### ISSUE TITLE
Services : Image Recorded User Testing sessions

### ISSUE THREAD

**Issue by VAli-designs** [VAli-designs/VAli-designs.github.io#7]
Est-il possible de recadrer l'image pour que la tete de l'utilisateur soit visible? 
En l'état actuel la tête est tronquée

**Comment by VAli-designs** [comment]
L'image couvre la totalité de l'espace disponible et est centré il faut adapté l'image a ces contraintes

**Comment by fdecampredon** [comment]
L'image couvre la totalité de l'espace disponible et est centré il faut adapté l'image a ces contraintes
